name: main

on:
  push:
    branches:
      - master

jobs:
  packages:
    runs-on: ubuntu-latest
    name: Check installed packages
    steps:
      - name: Check installed packages
        run: apt list --installed

  yq:
    runs-on: ubuntu-latest
    steps:
      - name: Check if yq is installed
        run: yq --help
